controllers:
    resource: ../src/Controller/
    type: attribute

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
#index:
#    path: /
#    controller: App\Controller\TestController::indexAction